### ISSUE TITLE
[upload] zm_dex

### ISSUE THREAD

**Issue by jeefo** [jeefo/yapb-graph#19]
User-created graph file has been uploaded for review.

Url: https://graph.yapb.ru/staging/zm_dex.graph
Map: zm_dex
Author: Drevny13
Nodes: 338

After marking this issue as resolved, graph will be uploaded to https://graph.yapb.ru/ database.

**Comment by Overitab** [comment]
как закрыть сделать resolved?

**Comment by jeefo** [comment]
Просто закрыть тикет.

**Comment by Overitab** [comment]
нет кнопки Close issue
если самому создать то можно

**Comment by jeefo** [comment]
В телеге напиши)
